{
 "title": "Overview 2",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "rate_interval", "label": "rate_interval", "query": "1m,5m,15m,30m,1h" }
  ]
 },
 "panels": [
  { "title": "Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "blackbox probe",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "probe_success", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Custom Exporter",
   "type": "gauge",
   "description": "Метрики из кастомного экспортера для Oncall",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "users_without_full_contacts",
     "legendFormat": "Пользователи с неполными контактами"
    },
    { "expr": "no_primary_today", "legendFormat": "Команды без primary-дежурных" },
    {
     "expr": "primaries_without_full_contacts",
     "legendFormat": "Primary с неполными контактами"
    }
   ]
  },
  {
   "title": "Last 10 logs (TOKEN)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "settings": { "limit": "10" }, "type": "logs" }
     ],
     "query": "_exists_:dissect.ip_address",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Last 10 logs (ALL)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "settings": { "limit": "10" }, "type": "logs" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "5xx HTTP STATUS",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "settings": { "limit": "10" }, "type": "logs" }
     ],
     "query": "dissect.status_code:[500 TO 599]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Error Count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "logback_events_total{level=\"error\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "USE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "CPU Utilizations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode!=\"idle\"}[$rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$rate_interval])))",
     "legendFormat": "CPU Utilization"
    }
   ]
  },
  {
   "title": "CPU Saturation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "rate(node_load1[$rate_interval])",
     "legendFormat": "load1"
    },
    {
     "expr": "rate(node_load5[$rate_interval])",
     "legendFormat": "load5"
    },
    {
     "expr": "rate(node_load15[$rate_interval])",
     "legendFormat": "load15"
    }
   ]
  },
  {
   "title": "RAM Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((avg_over_time(node_memory_MemAvailable_bytes[$__rate_interval]) * 100) / avg_over_time(node_memory_MemTotal_bytes[$__rate_interval]))",
     "legendFormat": "RAM utilization"
    }
   ]
  },
  {
   "title": "RAM Saturation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "rate(node_vmstat_pgmajfault[$rate_interval])",
     "legendFormat": "pgmajfault"
    },
    {
     "expr": "rate(node_vmstat_pgfault[$rate_interval])",
     "legendFormat": "pgfault"
    }
   ]
  },
  {
   "title": "Network Utilizations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total[$rate_interval])*8",
     "legendFormat": "receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total[$rate_interval])*8",
     "legendFormat": "transmit"
    }
   ]
  },
  {
   "title": "Network Saturation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_drop_total[$rate_interval])*8",
     "legendFormat": "receive drop"
    },
    {
     "expr": "irate(node_network_transmit_drop_total[$rate_interval])*8",
     "legendFormat": "transmit drop"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total[$rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Saturation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_weighted_seconds_total[$rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}