{
 "title": "SLA",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "SLA fail",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select name, local_date_time - interval '3h', is_good, value\r\nfrom sla\r\nwhere local_date_time between\r\n          date_trunc('day', now() + interval '3h')\r\n          and\r\n          date_trunc('day', now() + interval '3h' + interval '1d')\r\n  and is_good = false;"
    }
   ]
  },
  {
   "title": "Bad to All",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select ((select count(1)\r\n         from sla\r\n         where local_date_time between\r\n             date_trunc('day', now() + interval '3h')\r\n             and\r\n             date_trunc('day', now() + interval '3h' + interval '1d')\r\n           and is_good = false) / (6 * 1440::float8) * 100);"
    }
   ]
  },
  {
   "title": "sla_prober_get_teams_success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(sla_prober_get_teams_success_total[1m])",
     "legendFormat": "sla_prober_get_teams_success"
    }
   ]
  },
  {
   "title": "sla_prober_get_teams_fail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "increase(sla_prober_get_teams_fail_total[1m])",
     "legendFormat": "sla_prober_get_teams_fail"
    }
   ]
  },
  {
   "title": "sla_prober_create_user_success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "increase(sla_prober_create_user_success_total[1m])",
     "legendFormat": "sla_prober_create_user_success"
    }
   ]
  },
  {
   "title": "sla_prober_create_user_fail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "increase(sla_prober_create_user_fail_total[1m])",
     "legendFormat": "sla_prober_create_user_fail"
    }
   ]
  },
  {
   "title": "sla_prober_remove_user_success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "increase(sla_prober_remove_user_success_total[1m])",
     "legendFormat": "sla_prober_remove_user_success"
    }
   ]
  },
  {
   "title": "sla_prober_remove_user_fail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "increase(sla_prober_remove_user_fail_total[1m])",
     "legendFormat": "sla_prober_remove_user_fail"
    }
   ]
  }
 ]
}