version: '3'

services:
  oncall-web:
    build: .
    hostname: oncall
    ports:
      - "8080:8080"
      - "8888:8888"
    environment:
      - DOCKER_DB_BOOTSTRAP=1
      - IRIS_API_HOST=iris
    volumes:
      - ./configs/config.docker.yaml:/home/oncall/config/config.yaml
      - './textfile:/tmp/textfile'
    networks:
      - iris
  
  oncall-mysql:
    hostname: oncall-mysql
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    networks:
      - iris

  prometheus:
    image: prom/prometheus:v2.36.2
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=15d'
    ports:
      - "9090:9090"
    restart: always
    depends_on:
      - oncall-web
    networks:
      - iris

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    pid: host
    restart: unless-stopped
    ports:
      - "9100:9100"
    volumes:
      - './:/host:ro,rslave'
      - './textfile:/textfile'
    command:
      - "--path.rootfs=/host"
      - "--no-collector.arp" # кажется лишним, так я еще и сети не люблю
      - "--no-collector.conntrack" # метрики показывают, что не используется + /proc/sys/net/netfilter/ отсутствует
      - "--no-collector.dmi" # что-то про desktop, кажется не нужным + не используется
      - "--no-collector.fibrechannel" #  метрики показывают, что не используется
      - "--no-collector.hwmon" #  метрики показывают, что не используется
      - "--no-collector.infiniband" #  метрики показывают, что не используется
      - "--no-collector.ipvs" #  метрики нулевые + опять сети
      - "--no-collector.nfs" #  метрики показывают, что не используется
      - "--no-collector.nfsd" #  метрики показывают, что не используется
      - "--no-collector.nvme" #  метрики показывают, что не используется
      - "--no-collector.os" #  метрики показывают, что не используется
      - "--no-collector.powersupplyclass" #  не знаю, что такое
      - "--no-collector.pressure" #  метрики показывают, что не используется
      - "--no-collector.rapl" #  метрики показывают, что не используется
      - "--no-collector.tapestats" #  метрики показывают, что не используется
      - "--no-collector.zfs" #  метрики показывают, что не используется
      - "--collector.textfile.directory=/textfile"
    networks:
      - iris

  blackbox-exporter:
    image: quay.io/prometheus/blackbox-exporter:latest
    ports:
      - "9115:9115"
    command:
      - "--config.file=/etc/blackbox_exporter/config.yml"
    volumes:
      - ./configs/blackbox/blackbox.yml:/etc/blackbox_exporter/config.yml
    networks:
      - iris

networks:
  iris:
    name: iris
