version: '3.7'

services:
  oncall-web:
    build: .
    hostname: oncall
    ports:
      - "8080:8080"
      - "8888:8888"
    environment:
      - DOCKER_DB_BOOTSTRAP=1
      - IRIS_API_HOST=iris
    volumes:
      - ./configs/config.docker.yaml:/home/oncall/config/config.yaml
      - './textfile:/tmp/textfile'
      - 'oncall-filebeat:/home/oncall/var/log'
    depends_on:
      - oncall-mysql
      - prometheus
      - filebeat
  
  oncall-mysql:
    hostname: oncall-mysql
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=1234

  prometheus:
    image: prom/prometheus:v2.36.2
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=15d'
    ports:
      - "9090:9090"
    restart: always

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    pid: host
    restart: unless-stopped
    ports:
      - "9100:9100"
    volumes:
      - './:/host:ro,rslave'
      - './textfile:/textfile'
    command:
      - "--path.rootfs=/host"
      - "--no-collector.arp" # кажется лишним, так я еще и сети не люблю
      - "--no-collector.conntrack" # метрики показывают, что не используется + /proc/sys/net/netfilter/ отсутствует
      - "--no-collector.dmi" # что-то про desktop, кажется не нужным + не используется
      - "--no-collector.fibrechannel" #  метрики показывают, что не используется
      - "--no-collector.hwmon" #  метрики показывают, что не используется
      - "--no-collector.infiniband" #  метрики показывают, что не используется
      - "--no-collector.ipvs" #  метрики нулевые + опять сети
      - "--no-collector.nfs" #  метрики показывают, что не используется
      - "--no-collector.nfsd" #  метрики показывают, что не используется
      - "--no-collector.nvme" #  метрики показывают, что не используется
      - "--no-collector.os" #  метрики показывают, что не используется
      - "--no-collector.powersupplyclass" #  не знаю, что такое
      - "--no-collector.pressure" #  метрики показывают, что не используется
      - "--no-collector.rapl" #  метрики показывают, что не используется
      - "--no-collector.tapestats" #  метрики показывают, что не используется
      - "--no-collector.zfs" #  метрики показывают, что не используется
      - "--collector.textfile.directory=/textfile"
    depends_on:
      - prometheus

  blackbox-exporter:
    image: quay.io/prometheus/blackbox-exporter:latest
    ports:
      - "9115:9115"
    command:
      - "--config.file=/etc/blackbox_exporter/config.yml"
    volumes:
      - ./configs/blackbox/blackbox.yml:/etc/blackbox_exporter/config.yml
    depends_on:
      - prometheus

  elasticsearch:
    image: elasticsearch:${STACK_VERSION}
    labels:
      co.elastic.logs/enabled: false
    volumes:
      - './elk/elastic_data:/usr/share/elasticsearch/data/'
    ports:
      - '9200:9200'
    environment:
      discovery.type: single-node
      ELASTIC_USERNAME: elastic
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      ES_JAVA_OPTS: '-Xms256m -Xmx256m'

  logstash:
    image: logstash:${STACK_VERSION}
    labels:
      co.elastic.logs/enabled: false
    volumes:
      - './elk/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf'
    ports:
      - "5044:5044"
    environment:
      LS_JAVA_OPTS: '-Xmx256m -Xms256m'
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:${STACK_VERSION}
    labels:
      co.elastic.logs/enabled: false
    ports:
      - '5601:5601'
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: ${ELASTIC_PASSWORD}
    depends_on:
      - elasticsearch

  filebeat:
    image: elastic/filebeat:${STACK_VERSION}
    labels:
      co.elastic.logstash/enabled: false
    command: filebeat -e -strict.perms=false
    volumes:
      - 'oncall-filebeat:/home/oncall/var/log'
      - './elk/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro'
      - '/var/lib/docker/containers:/var/lib/docker/containers:ro'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    depends_on:
      - logstash

  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    depends_on:
      - prometheus
      - elasticsearch

volumes:
  oncall-filebeat:
