filebeat.inputs:
  - type: log
    paths:
      - /home/oncall/var/log/*/*.log

filebeat.autodiscover:
  providers:
    type: docker
    hints.enabled: true

processors:
  - dissect:
      tokenizer: "%{timestampTZ} [%{status_code|integer}] %{http_method} %{endpoint} %{ip_address} [%{user_agent}] RT:%{rt|integer} REF:%{ref} SZ:%{sz|integer} %{protocol}"
      field: "message"
      target_prefix: "dissect"
  - drop_fields:
      fields: [ "dissect.timestampTZ", "dissect.http_method", "dissect.endpoint", "dissect.user_agent", "dissect.rt", "dissect.ref", "dissect.sz", "dissect.protocol"]
      ignore_missing: true
  - add_docker_metadata:

output.logstash:
  hosts: [ "logstash:5044" ]
